### ISSUE TITLE
htp_unparse_uri_noencode() is private

### ISSUE THREAD

**Issue by b1v1r** [OISF/libhtp#40]
The htp_unparse_uri_noencode() function is private and required to generate a normalized URI, which was removed in 0.5. Please make this and other similar functions public for 0.5.

**Comment by ivanr** [comment]
That particular function is not used in LibHTP and I suggest that you migrate it into IronBee.

There's a bunch of ad-hoc utility functions in LibHTP that may or may not be useful, but they need to be reviewed before they become part of the API. I don't want to expose all of them and I also don't know which ones you might need in IronBee.

I would like to see a good set of utility functions in a future LibHTP release, but that will require some planning so that the set as a whole makes sense. In the meantime, if you need any functions that are used in LibHTP, please feel free to move them to htp.h, but with a note that they are likely to change in the future.
