### ISSUE TITLE
htp_unparse_uri_noencode is in header, but not implemented

### ISSUE THREAD

**Issue by b1v1r** [OISF/libhtp#47]
htp_unparse_uri_noencode() is in the header, but not implemented in the C file.  IronBee used this private function (probably should not have), but this caused the code to compile fine, but fail at runtime when symbol not found.  I suggest leaving the function implemented in 0.5.x, deprecate and then remove in a later version.

**Comment by ivanr** [comment]
The function is now back in 0.5.x. I didn't make it public; if it worked for you before it should work for you now.

I do have a question about URL-decoding the query string: do you want it? Because of some refactoring the code changed, and so the current htp_unparse_uri_noencode() will not perform any transformations on the query string. If that's fine with you, please close the ticket.

The underlying issue is that there are many ways to configure URL-decoding. Any one fixed configuration will be wrong. To do it correctly, we'd need to change the function signature to pass a configuration object and a configuration context.

**Comment by b1v1r** [comment]
Looks good.  Essentially I just the URL reassembled with host/path normalization.  Query string should remain the same.
